In [91]:
import numpy as np
# 1.Utwórz tablicę zawierającą 50 piątek
table_z1 = np.full(50,5)
print("Zad.1:\n",table_z1)


Zad.1:
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5]


In [92]:
# 2.Utwórz tablicę 5x5 z wartościami od 1 do 25
table_z2 = np.arange(1, 26).reshape((5, 5))
print("Zad.2:\n",table_z2)

Zad.2:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [93]:
# 3.Utwórz tablicę liczb parzystych od 10 do 50
table_z3 = np.arange(10,51,2)
print("Zad.3:\n",table_z3)

Zad.3:
 [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [94]:
# 4.Utwórz macierz w której na przekątnej znajdą  się wartości równe 8 a pozostałe będą równe 0
matrix_z4 = np.eye(5)*8
print("Zad.4:\n",matrix_z4)

Zad.4:
 [[8. 0. 0. 0. 0.]
 [0. 8. 0. 0. 0.]
 [0. 0. 8. 0. 0.]
 [0. 0. 0. 8. 0.]
 [0. 0. 0. 0. 8.]]


In [95]:
# 5.Utwórz tablicę o rozmiarach 10x10 z wartościami zwiększajacymi sie o 0.01
table_z5 = np.arange(0,1,0.01).reshape(10,10)
print("Zad.5: \n",table_z5)

Zad.5: 
 [[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09]
 [0.1  0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19]
 [0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29]
 [0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39]
 [0.4  0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49]
 [0.5  0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59]
 [0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69]
 [0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79]
 [0.8  0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89]
 [0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99]]


In [98]:
# 6.Utworzyć przestrzeń liniową 50 wartości z zakresu od 0 do 1
linspace_z6 = np.linspace(0,1,50)
print("Zad.6: \n",linspace_z6)

Zad.6: 
 [0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [110]:
# 7.Wybierz podtablice 12-elementowa z tablicy utworzonej w  zad.2 z wartosciami w zakresie 12-25
table_z7 = table_z2[(table_z2 >=12)][0:12]
print("Zad. 7:\n",table_z7)

Zad. 7:
 [12 13 14 15 16 17 18 19 20 21 22 23]


In [109]:
# 8.Wybrać 3 pierwsze elementy z ostatniej kolumny tablicy utworzonej w zadaniu 2, a następnie ułożyć z nich kolumnę.
table_z8 = table_z2[:3,-1]
table_z8 = table_z8.reshape((3,1))
print("Zad. 8:\n",table_z8)

Zad. 8:
 [[ 5]
 [10]
 [15]]


In [101]:

# 9. Wyznaczyć sumę wartości elementów znajdujących się w dwóch ostatnich wierszach macierzy utworzonej w zadaniu 2.
table_z9 = table_z2[:3,-1]
sum_z9 = np.sum(table_z2[-2:,:])
print("Zad. 9:\n suma wynosi",sum_z9)

Zad. 9:
 suma wynosi 205


In [102]:
# 10.Przygotować skrypt, który stworzy tensor zawierający losowe wartości całkowite, losowym wymiarze i losowym rozmiarze każdego z wymiarów.
num_dimensions = np.random.randint(1, 5) #od 1 do 4 wymiarow (dla ograniczenia obliczen)
shape = tuple(np.random.randint(2, 8, size=num_dimensions)) #od 2 do 7 rozmiar wymiaru (dla ograniczenia obliczen)
tensor_z10 = np.random.randint(0, 10, size=shape) 
print("Zad.10:\n",tensor_z10)

Zad.10:
 [[[[5 7 6 1 4 1]
   [9 4 6 2 8 3]]

  [[5 6 4 3 4 0]
   [0 1 0 0 0 9]]]


 [[[6 0 6 7 6 0]
   [0 0 4 5 3 5]]

  [[4 1 9 0 9 7]
   [9 6 7 0 0 8]]]


 [[[6 9 0 9 2 6]
   [3 5 6 6 4 6]]

  [[3 3 5 8 9 6]
   [1 5 3 4 5 2]]]


 [[[8 0 6 7 9 3]
   [4 4 8 1 0 3]]

  [[7 6 3 6 1 6]
   [3 2 3 2 2 8]]]


 [[[5 5 5 9 2 8]
   [7 5 9 3 7 0]]

  [[9 8 0 2 7 7]
   [2 9 4 0 8 0]]]]


In [103]:
# 11.Przygotować macierz, która w każdym wierszu będzie zawierała wartości od 1 do 5. Uwaga, nie używać w tym celu gotowych list do utworzenia macierzy.
rows = 4 #ile ma miec wierszy
matrix_z11 = np.tile(np.arange(1, 6), (rows, 1))
print("Zad.11:\n",matrix_z11)

Zad.11:
 [[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [104]:
# 12.Utworzyć wektor 10-elementowy składający się z wartości losowych, a następnie wstawić 0 w miejsce wartości najmniejszej.
vector_z12 = np.random.rand(10)
min_value_index = np.argmin(vector_z12)
vector_z12[min_value_index] = 0
print("Zad.12:\n",vector_z12)

Zad.12:
 [0.50070587 0.54426549 0.55319169 0.70279521 0.80126518 0.52279078
 0.9000036  0.57227569 0.81156647 0.        ]


In [105]:
# 13.Napisać skrypt, który w losowym wektorze Z znajdzie najbliższą wartość losowego skalara v.
Z = np.random.rand(10)
v = np.random.rand()

# Znajdź indeks najbliższej wartości w wektorze Z do skalaru v
closest_index = np.abs(Z - v).argmin()
closest_value = Z[closest_index]


print("Zad.13:\n", "wektor:",Z,",\n", "skalar:",v,",\n", "Najbliższa wartość w wektorze Z do skalaru v:", closest_value)

Zad.13:
 wektor: [0.73848332 0.02113754 0.04035125 0.6007129  0.83725254 0.77662527
 0.67886057 0.35541235 0.69990015 0.2307776 ] ,
 skalar: 0.09360816477286249 ,
 Najbliższa wartość w wektorze Z do skalaru v: 0.040351247155556824


In [106]:
# 14.Wygenerować losową macierz M o rozmiarach 5x8, a następnie zamienić kolejnością 2 losowo wskazane wiersze.
M = np.random.rand(5, 8)

# Wybierz losowo dwa różne indeksy wierszy
row_indices = np.random.choice(5, 2, replace=False)
print("Zad.14: \nPoczątkowa macierz M:")
print(M)

# Zamień kolejnością wybrane wiersze
M[row_indices[0], :], M[row_indices[1], :] = M[row_indices[1], :], M[row_indices[0], :].copy()
print("\nMacierz M po zamianie wierszy:")
print(M)

Zad.14: 
Początkowa macierz M:
[[2.91865243e-01 8.28606788e-01 9.37163260e-01 7.32337272e-01
  7.33327862e-01 4.35357734e-01 1.33165597e-01 7.12283170e-01]
 [4.44622260e-01 4.25066164e-01 7.90915735e-01 4.84358155e-01
  5.15692405e-01 9.35944403e-01 6.44478499e-02 7.14081687e-01]
 [6.49525286e-01 8.20981243e-01 5.15303984e-01 5.13425369e-01
  2.93343451e-01 5.09787705e-01 7.87344601e-01 7.36306059e-01]
 [3.77654412e-04 7.85606546e-01 4.40591731e-01 5.24552812e-01
  4.05934703e-01 3.20722603e-02 5.41250186e-02 8.32745719e-02]
 [4.15747865e-01 5.89924783e-01 4.51050792e-01 6.81157987e-03
  3.35710177e-01 4.64912234e-01 4.51306381e-01 2.97502969e-01]]

Macierz M po zamianie wierszy:
[[2.91865243e-01 8.28606788e-01 9.37163260e-01 7.32337272e-01
  7.33327862e-01 4.35357734e-01 1.33165597e-01 7.12283170e-01]
 [4.44622260e-01 4.25066164e-01 7.90915735e-01 4.84358155e-01
  5.15692405e-01 9.35944403e-01 6.44478499e-02 7.14081687e-01]
 [3.77654412e-04 7.85606546e-01 4.40591731e-01 5.24552812e-01

In [107]:
# 15.Wygenerować macierz o rozmiarach 5x5 wypełnioną dowolnymi kolejnymi wartościami, a następnie przetransformować macierz do postaci wektora kolumnowego zachowując wszystkie wartości.
matrix_5x5 = np.arange(1, 26).reshape((5, 5))
print("Zad.15: \nPoczątkowa macierz 5x5:")
print(matrix_5x5)

# macierz do postaci wektora kolumnowego
vector_column = matrix_5x5.flatten(order='F')  # 'F' oznacza zamianę kolumnowo (kolumny są czytane w kolejności)
print("\nWektor kolumnowy:")
print(vector_column)

Zad.15: 
Początkowa macierz 5x5:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Wektor kolumnowy:
[ 1  6 11 16 21  2  7 12 17 22  3  8 13 18 23  4  9 14 19 24  5 10 15 20
 25]
